### ISSUE TITLE
 Error connecting to spectrum server: dial tcp 127.0.0.1:1234:

### ISSUE THREAD

**Issue by Elderwolf1700** [allangood/rtlamr2mqtt#231]
I run this command to find my meter `~ docker run --rm -ti -e LISTEN_ONLY=yes -e RTL_MSGTYPE="all" -e RTL_TCP_ARGS="-d 777" --device=/dev/bus/usb:/dev/bus/usb allangood/rtlamr2mqtt
` 
but get an error code of:

`[2024-04-22 09:05:38] Starting in LISTEN ONLY Mode...
[2024-04-22 09:05:38] No Supervisor detected.
[2024-04-22 09:05:38] Starting rtl_tcp with /usr/bin/rtl_tcp -d 777
[2024-04-22 09:05:40] Starting rtlamr with ['/usr/bin/rtlamr', '-msgtype=all', '-format=json']
[2024-04-22 09:05:40] You should see all utility meters after this line:
[2024-04-22 09:05:40] 09:05:40.143308 main.go:90: Error connecting to spectrum server: dial tcp 127.0.0.1:1234: connect: connection refused
[2024-04-22 09:05:40] rcvr.Connect`
`[2024-04-22 09:05:40] main.(*Receiver).NewReceiver
[2024-04-22 09:05:40]   /go/pkg/mod/github.com/bemasher/rtlamr@v0.9.3/main.go:90
[2024-04-22 09:05:40] main.main
[2024-04-22 09:05:40]   /go/pkg/mod/github.com/bemasher/rtlamr@v0.9.3/main.go:313
[2024-04-22 09:05:40] runtime.main
[2024-04-22 09:05:40]   /usr/local/go/src/runtime/proc.go:267
[2024-04-22 09:05:40] runtime.goexit
[2024-04-22 09:05:40]   /usr/local/go/src/runtime/asm_arm64.s:1197`

`2024-04-22 09:11:30] Shutdown detected, killing process.
Traceback (most recent call last):
  File "/usr/bin/rtlamr2mqtt.py", line 415, in <module>
    listen_mode()
  File "/usr/bin/rtlamr2mqtt.py", line 392, in listen_mode
    for amrline in rtlamr.stdout:
  File "/usr/local/lib/python3.10/codecs.py", line 319, in decode
    def decode(self, input, final=False):
  File "/usr/bin/rtlamr2mqtt.py", line 152, in shutdown
    if not external_rtl_tcp and rtltcp.returncode is None:
NameError: name 'external_rtl_tcp' is not defined`

Got it to show once before in testing but now it just keeps giving me this error. Am I doing something wrong or is this just not working?
Btw, yes its connected to a powered hub.

**Comment by Nurgak** [comment]
I just had the same issue, turned out I was already using the device from another container (`rtl_433`).

It was just a matter for shutting down the other container and freeing the device for `rtlamr`. So make sure your device is not used by another process.

**Comment by allangood** [comment]
I will close this as preparation for the next release.
